name: PlatformIO CI

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - dev

jobs:
  pio-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4.2.2

      - name: Checkout UI
        run: |
          echo "Checkout UI"
          git clone https://github.com/mp-se/gravitymon-gateway-ui gravitymon-gateway-ui 
          cp gravitymon-gateway-ui/dist/assets/style.css.gz html/app.css.gz
          cp gravitymon-gateway-ui/dist/assets/index.js.gz html/app.js.gz
          cp gravitymon-gateway-ui/gravitymon-gateway.html html/index.html
          cp gravitymon-gateway-ui/dist/favicon.ico html/favicon.ico
          gzip -f html/favicon.ico

          # echo "Checkout shared code"
          # git clone -b dev https://github.com/mp-se/gravitymon gravitymon-gateway 
          # rm ./src/*
          # rm ./lib/espfwk/*
          # cp -R gravitymon-gateway/lib/ ./
          # cp -R gravitymon-gateway/src/ ./
          # cp -R gravitymon-gateway/script/ ./
          # cp -R gravitymon-gateway/boards/ ./
          # cp gravitymon-gateway/platformio.ini ./platformio.ini

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Setup PlatformIO
        run: pip install platformio

      - name: Build gateway32pro-tft
        run: pio run -e gateway32pro-tft

      - name: Build gateway32s3pro-tft-sd
        run: pio run -e gateway32s3pro-tft-sd

      - name: Build gateway32s3wave-tft28-sd
        run: pio run -e gateway32s3wave-tft28-sd

      - name: Build gateway32s3wave-tft43-sd
        run: pio run -e gateway32s3wave-tft43-sd
    
      - uses: EndBug/add-and-commit@v10 # You can change this to use a specific version. https://github.com/marketplace/actions/add-commit
        with:
          add: 'bin html'
          author_name: GitHub Action
          author_email: mp-se@noreply.github.com
          default_author: github_actor
          message: 'GitHub Action Build'
          pathspec_error_handling: ignore
