name: PlatformIO CI

on: 
  push:
    branches: 
      - dev
      - master

jobs:
  pio-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Checkout UI
        run: |
          echo "Checkout UI"
          git clone https://github.com/mp-se/gravitymon-blegw-ui gravitymon-blegw-ui 
          cp gravitymon-blegw-ui/dist/assests/style.css.gz html/app.css.gz
          cp gravitymon-blegw-ui/dist/assests/js/index.js.gz html/app.js.gz

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1.0.1    

      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: "gw-pro-release,gw-s3pro-release,gw-c3-release,gw-s3-release"
          #targets: ""
          #project-dir: "./some_dir"
          #project-conf: "./some_dir/custom.ini"
          jobs: 6
          silent: false
          verbose: true
          disable-auto-clean: false
    
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version. https://github.com/marketplace/actions/add-commit
        with:
          add: 'bin html'
          author_name: GitHub Action
          author_email: mp-se@noreply.github.com
          default_author: github_actor
          message: 'GitHub Action Build'
          pathspec_error_handling: ignore
          